[/Script/EngineSettings.GameMapsSettings]
; Set EditorStartupMap and GameDefaultMap to /Game/Maps/M_Room00_Tutorial after the map exists.
; Set GlobalDefaultGameMode to BP_SimRoomGameMode after creating the Blueprint asset.

[/Script/Engine.RendererSettings]
r.DefaultFeature.AutoExposure=False
