[/Script/EngineSettings.GameMapsSettings]
; Set EditorStartupMap and GameDefaultMap to /Game/Maps/M_Room00_Tutorial after the map exists.
GlobalDefaultGameMode=/Script/SimRoom.SimRoomGameMode

[/Script/Engine.RendererSettings]
r.DefaultFeature.AutoExposure=False
